### ISSUE TITLE
initial setup script errors

### ISSUE THREAD

**Issue by fatalglitch** [vaeyo/PlexServerDockerfiles#1]
Sed command throws errors when running

root@server:/srv# ./initial.setup.sh
Your username? This if for ownership and permissions of containers: dockeruser
Enter email address for SSL cerificates and Press [Enter]: email@domain.com
We need your domain root for the SSL certs
i.e example.com or mysite.com, avoid www.example.com or https:// etc..
Enter the domain youd like to secure and press [Enter]: somedomain.com
./initial.setup.sh: line 15: ----------------: command not found
sed: -e expression #1, char 16: unknown option to `s'
sed: -e expression #1, char 16: unknown option to `s'
sed: -e expression #1, char 16: unknown option to `s'
sed: -e expression #1, char 16: unknown option to `s'

**Comment by callahant** [comment]
More detail turning on the verbose debug of bash

#!/bin/bash -vx

read -p "Your username? This if for ownership and permissions of containers: " uname
+ read -p 'Your username? This if for ownership and permissions of containers: ' uname
Your username? This if for ownership and permissions of containers: dockeruser
read -p "Enter email address for SSL cerificates and Press [Enter]: " emails
+ read -p 'Enter email address for SSL cerificates and Press [Enter]: ' emails
Enter email address for SSL cerificates and Press [Enter]: me@home.com

uid=$(id -u $uname)
id -u $uname
++ id -u dockeruser
+ uid=911
gid=$(id -g $uname)
id -g $uname
++ id -g dockeruser
+ gid=911
tz="$(cat /etc/timezone)"
cat /etc/timezone
++ cat /etc/timezone
+ tz=America/New_York

echo "We need your domain root for the SSL certs"
+ echo 'We need your domain root for the SSL certs'
We need your domain root for the SSL certs
echo "i.e example.com or mysite.com, avoid www.example.com or https:// etc.."
+ echo 'i.e example.com or mysite.com, avoid www.example.com or https:// etc..'
i.e example.com or mysite.com, avoid www.example.com or https:// etc..
read -p "Enter the domain youd like to secure and press [Enter]: " domain
+ read -p 'Enter the domain youd like to secure and press [Enter]: ' domain
Enter the domain youd like to secure and press [Enter]: domain.com

# Make the edits
----------------
+ ----------------
./initial.setup.sh: line 15: ----------------: command not found
# UID
sudo find . -type f -name "*.env" -exec sed -i "s/-uid-/"$uid"/g" '{}' \;
+ sudo find . -type f -name '*.env' -exec sed -i s/-uid-/911/g '{}' ';'
# GID
sudo find . -type f -name "*.env" -exec sed -i "s/-gid-/"$gid"/g" '{}' \;
+ sudo find . -type f -name '*.env' -exec sed -i s/-gid-/911/g '{}' ';'
# TZ
sudo find . -type f -name "*.env" -exec sed -i "s/-tz-/"$tz"/g" '{}' \;
+ sudo find . -type f -name '*.env' -exec sed -i s/-tz-/America/New_York/g '{}' ';'
sed: -e expression #1, char 16: unknown option to `s'
sed: -e expression #1, char 16: unknown option to `s'
sed: -e expression #1, char 16: unknown option to `s'
sed: -e expression #1, char 16: unknown option to `s'
# Email
sudo find . -type f -exec sed -i "s/email@somedomain.com/"$emails"/g" '{}' \;
+ sudo find . -type f -exec sed -i s/email@somedomain.com/me@home.com/g '{}' ';'
# domain
sudo find . -type f -exec sed -i "s/somedomain.com/"$domain"/g" '{}' \;
+ sudo find . -type f -exec sed -i s/somedomain.com/domain.com/g '{}' ';'

**Comment by fatalglitch** [comment]
Fix for this issue is in Pull request #2

**Comment by vaeyo** [comment]
merged. Thank you.
