### ISSUE TITLE
pull access denied for vaeyo/rtorrent, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by micheldlebeau** [vaeyo/PlexServerDockerfiles#5]
https://github.com/vaeyo/PlexServerDockerfiles/blob/4f58a87ee05341a937ee33f4da561e5b1b913209/rtorrent/docker-compose.yml#L5

Is that a public image?

**Comment by gladroger** [comment]
same here

**Comment by vaeyo** [comment]
Was listed under a different name. I am repushing it now under the correct user. Sorry for the error.

**Comment by vaeyo** [comment]
Just pulled it and started it. No issues here. Sorry for the inconvenience. Ill be pushing an update to it later today that adds a couple ruTorrent plugins/themes.
